[package]
name = "vhallway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
rocket = { version = "0.5.0-rc.1" }
rocket_auth = { version = "0.4.0", features = ["tokio-postgres"] }
